# Generated by Django 3.1.1 on 2020-09-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_index=True, max_length=20, verbose_name='Штрих Код')),
                ('lm', models.CharField(db_index=True, max_length=10, verbose_name='ЛМ код')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='FoundGoods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер заявки')),
                ('bar_code', models.CharField(db_index=True, help_text='Отсканируйте штрих-код', max_length=50, verbose_name='ШтрихКод')),
                ('lm_code', models.CharField(db_index=True, max_length=15, verbose_name='ЛМ-код')),
                ('caption', models.CharField(max_length=50, verbose_name='Наименование')),
                ('amount_goods', models.FloatField(null=True, verbose_name='Количество')),
                ('note_add', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заметка')),
                ('shop_num', models.PositiveSmallIntegerField(verbose_name='Номер магазина')),
                ('create_at', models.DateField(auto_now_add=True, db_index=True, verbose_name='найден')),
                ('update_at', models.DateField(blank=True, db_index=True, help_text='Пожалуйста, используйте следующий формат: <em>ДД-ММ-ГГГГ</em>.', null=True, verbose_name='выдан')),
            ],
            options={
                'verbose_name': 'Забытый товар',
                'verbose_name_plural': 'Забытые товары',
                'ordering': ['-create_at'],
            },
        ),
    ]
