# Generated by Django 3.1.1 on 2020-09-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0002_foundgoods_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundgoods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_user', to='accounts.customuser', verbose_name='Пользователь'),
        ),
    ]
