# Generated by Django 3.1.1 on 2020-09-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200914_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundgoods',
            name='shop_num',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер магазина'),
        ),
    ]
