# Generated by Django 3.1.1 on 2020-09-15 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0004_auto_20200915_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundgoods',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
