# Generated by Django 3.1.1 on 2020-09-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20200915_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundgoods',
            name='bar_code',
            field=models.CharField(db_index=True, help_text='штрихкод', max_length=50, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='foundgoods',
            name='update_at',
            field=models.DateField(blank=True, db_index=True, help_text='Пожалуйста, используйте следующий формат: <em>ДД.ММ.ГГГГ</em>.', null=True, verbose_name='выдан'),
        ),
    ]
