# Generated by Django 3.1.1 on 2020-09-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20200920_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundgoods',
            options={'verbose_name': 'Забытый товар', 'verbose_name_plural': 'Забытые товары'},
        ),
    ]
