# Generated by Django 3.1.1 on 2020-10-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_auto_20200922_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundgoods',
            name='bar_code',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Штрихкод'),
        ),
    ]
